### ISSUE TITLE
list parameters are not slugified

### ISSUE THREAD

**Issue by aadu** [miku/gluish#1]
Gluish is a great addition to luigi! I have noticed that list parameters are not properly sluggified. For example a task that takes a list like `['cd', 'statesd', 'dma', 'county']` resulted in the following filename: `geo-["'cd'", "'statesd'", "'dma'", "'county'"]-state-nd.h5`.

I think this might be rectified by adding a delist function:
```
def delist(x):
    if type(x) is list:
        return '-'.join(sorted(x))
    else:
        return x

parts = ('{k}-{v}'.format(k=k, v=delist(v))
                     for k, v in task_params.iteritems())
```
or something like this:
```
parts = []
 for k, v in task_params.iteritems():    
    if type(v) == list:
        v = '-'.join(sorted(v))
    parts.append('{k}-{v}'.format(k=k, v=v))
```

**Comment by miku** [comment]
Thanks for your input and sorry for commenting late. It shows, that we do not use list parameters. I'll try to look into this shortly.

**Comment by miku** [comment]
[0.1.71](https://pypi.python.org/pypi/gluish/0.1.71) should fix this issue for now.

**Comment by aadu** [comment]
Thanks! Works beautifully.
