### ISSUE TITLE
Encapsulate _init__ imports in try/catch (individually)

### ISSUE THREAD

**Issue by kutschkem** [miku/gluish#3]
On Windows, it is an incredible pain to install sqlitebck. Because of that, I opted for installing gluish without dependencies, and just use the parts that I needed.

However, this cherry-picking approach does not work because you import all the sub-modules in the _init__.py - this makes import fail no matter what parts I actually want to use, because this means all the dependencies have to be present.

I have two alternative solutions:

Solution 1: Don't import in **init**.py like you do.
Solution 2: Make the imports conditional, enclose them in try/catch like here: http://stackoverflow.com/a/3496790/1319284. This means convenient imports if the dependencies are there, no convenient imports otherwise.

**Comment by miku** [comment]
Indeed, gluish needs a bit of cleanup. Especially, I would like to reduce the code to the core luigi additions: task, format, parameter and a few utils.

**Comment by miku** [comment]
b715cec518252e0a10402363f06434c989e1f66a should mitigate the sqlitebck issue a bit. I uploaded a minor update [0.1.72](https://pypi.python.org/pypi/gluish/0.1.72) to pypi.

**Comment by miku** [comment]
I plan to do some [streamlining in 0.2](https://github.com/miku/gluish/issues/4). Please feel free to add anything you might miss.

**Comment by kutschkem** [comment]
0.2 seems a lot more self-contained now, so I guess this issue can be closed?

**Comment by miku** [comment]
Yes, indeed. Thanks for the reminder. We use gluish in production and it mainly works w/o many adjustments, that's why haven't revisited this issue.
