### ISSUE TITLE
shellout broken

### ISSUE THREAD

**Issue by kutschkem** [miku/gluish#6]
I am on Windows, and just went through a long session of debugging a shellout call, which failed because of "File not found" problems. The problem, I think, is that the command is given to subprocess.call as one big blob, which I think gets interpreted as the command file name. This problem appears on Windows, at the very least with cygwin.

**Comment by miku** [comment]
Sorry, for the moment, `shellout` is Unix-only.

> as one big blob, which I think gets interpreted as the command file name.

I believe I implemented it this way to quickly have support for pipes - which also entails the [pipefail](https://github.com/miku/gluish/blob/ec9254e67106e8a0b4725a64d0948b0ea2b3a4e4/gluish/utils.py#L131) addition - which ensures that the shell always exits with non-zero status on errors.

Happily accepting PR for Windows support, but I cannot test or support it at the moment.
